# Generated by Django 3.2.8 on 2024-10-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100, verbose_name='nombreC')),
                ('descripcion', models.TextField(max_length=100, verbose_name='descripionC')),
            ],
        ),
    ]
