name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4.3
        env:
          MYSQL_ROOT_PASSWORD: Adavid02  # Contraseña del root
          MYSQL_DATABASE: crud_nuevo      # Nombre de la base de datos
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-timeout=5m --health-retries=3

    steps:
      - uses: actions/checkout@v2  # Clona el repositorio

      # Configuración de Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django/CRUD/requirements.txt

      # Configura las variables de entorno para Django
      - name: Set environment variables for Django
        run: |
          echo "DATABASE_URL=mysql://root:Adavid02@127.0.0.1:3306/crud_nuevo" >> $GITHUB_ENV

      # Ejecutar las migraciones de Django
      - name: Run migrations
        working-directory: ./django/CRUD
        run: |
          python manage.py migrate

      # Ejecutar pruebas
      - name: Run tests
        run: |
          python manage.py test
