# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: Adavid02
          MYSQL_USER: root
          MYSQL_PASSWORD: Adavid02
          MYSQL_DATABASE: crud_nuevo
        ports:
          - 3306:3306
        options: > 
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -pAdavid02" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean up Docker containers
      run: |
        docker ps -aq | xargs -r docker stop | xargs -r docker rm

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mysqlclient  # Conector de MySQL para Python

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -u root -pAdavid02 --silent; do
          echo "Waiting for database connection..."
          sleep 3
        done

    - name: Set environment variables
      run: |
        echo "DATABASE_URL=mysql://root:Adavid02@127.0.0.1:3306/crud_nuevo" >> $GITHUB_ENV
        echo "SECRET_KEY=test_secret_key" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test

    - name: Inspect Docker logs
      if: failure()
      run: docker logs $(docker ps -q -f name=db)
