name: Django CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: Adavid02
          MYSQL_DATABASE: crud_nuevo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -pAdavid02"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_NAME: crud_nuevo
      DB_USER: root
      DB_PASSWORD: Adavid02
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y default-mysql-client

      - name: List Active Containers
        run: docker ps -a

      - name: Test MySQL Connection
        run: |
          mysqladmin ping -h 127.0.0.1 -u root -pAdavid02 --silent || exit 1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django/CRUD/requirements.txt

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -pAdavid02 --silent; then
              echo "Database is up!"
              break
            else
              echo "Waiting for database connection..."
              sleep 5
            fi
          done
          if ! mysqladmin ping -h 127.0.0.1 -u root -pAdavid02 --silent; then
            echo "Could not connect to database."
            docker logs ${{ job.services.mysql.id }}
            exit 1
          fi

      - name: Apply Migrations
        run: |
          cd django/CRUD
          python manage.py migrate

      - name: Run Django Tests
        run: |
          cd django/CRUD
          python manage.py test
